from omegaconf import OmegaConf

cfg = {
    "description": "Final Affinity model",
    "precision": "bf16-mixed",
    "num_devices": 1,
    "num_epochs": 10,
    "save_log_weights_interval": 1,
    "train_metric_interval": 1,
    'val_interval': 0.5,
    "inference_epochs": [],
    "model_checkpoint_at": "checkpoints",
    "img_size": 1024,
    "out_dir": "/",
    "focal_wt": 20,
    "num_tokens": 0,
    "dense_reg_wt": 0,
    "result_dir": "",
    "opt": {
        "learning_rate": 4e-4,
        "min_learning_rate": 1e-5,
        "auto_lr": False,
        "weight_decay": 0.01,
    },
    "model": {
        "type": "vit_l",
        "checkpoint": "sam_vit_l_0b3195.pth",
        "requires_grad": {
            "image_encoder": False,
            "prompt_encoder": False,
            "mask_decoder": False,
            "propagation_module": True,
        },
        "multimask_output": True,
        "propagation_ckpt": None,
    },
    "dataset": {
        "name": "moca",
        "root_dir": "raw/",
        "stage1": False,
        "train_batch_size": 8,
        "val_batch_size": 8,
        "max_num_obj": 1,
        "num_frames": 3,
        "max_jump": 1,
        "num_workers": 4,
        "pin_memory": True,
        "persistent_workers": True,
    },
}
cfg = OmegaConf.create(cfg)